In [1]:
import pandas as pd
from tqdm import tqdm
import ast

In [31]:
ingr_df = pd.read_csv('../data/ingr.csv')
ingr_df

,title,food,quantity,unit
0,Infineon Raceway Baked Beans,"['skirt steak', 'pepper', 'bacon', 'onion', 'j...","['2', None, 'about 1', '1 1/2', '2', '3', '1',...","['pounds', None, 'cup', 'cups', 'cup', 'tables..."
1,Sour Cream Noodle Bake,"['chuck', 'tomato sauce', 'salt', 'pepper', 'e...","['1 1/4', '15', '1/2', None, '8', '1/2', '1 1/...","['pounds', 'can', 'teaspoon', None, 'ounces', ..."
2,Middle-Eastern Eggplant Rounds,"['olive oil', 'baby Italian eggplants', 'Koshe...","['1', '6', None, '1/2', '4', '2', '1']","['tablespoon', 'ounces', None, 'cup', None, 't..."
3,Saffron Jewel Rice,"['saffron threads', 'sugar', 'Kosher salt', 'o...","['1/2', '1/3', None, '2', '1', '4', '1', '1', ...","['teaspoon', 'cup', None, 'strips', None, 'tab..."
4,Thai Sweet and Sour Wings,"['chili sauce', 'rice vinegar', 'Asian fish sa...","['2', '1', '2', '1', '1', '2', None, '1', '18 ...","['cups', 'cup', 'tablespoons', 'tablespoon', '..."
...,...,...,...,...
30920,Spicy Agave Wave,"['Ice', 'jalapeno', 'lime juice', 'lemon juice...","[None, '1', '1-', '1/2-ounce', '1 1/2', '3/4',...","[None, 'slice', 'ounce', None, 'ounces', 'ounc..."
30921,Apple Chimichangas,"['butter', 'sugar', 'cinnamon', 'apple', 'pear...","['1/4', '1/3', '1', '1', '1', '1/4', '4', '1',...","['cup', 'cup', 'teaspoon', None, None, 'cup', ..."
30922,Summer Corn Salad,"['corn', 'Belgian endive', 'olive oil', 'peppe...","['4', '2', '2', None, '3', '1/2', '1/4', '1/2'...","['ears', 'heads', 'tablespoons', None, 'bunch'..."
30923,Zucchini Stuffed Tomatoes,"['plum tomatoes', 'sugar', 'zucchini', 'salt',...","['4', None, '1 1/2', '1', '3', '2', '3', '1 1/...","[None, None, 'pounds', 'teaspoon', None, 'tabl..."
30924,Crabby Bisque,"['crab bisque', 'heavy cream', 'lemon juice', ...","['10.5', '6', '3', '3', '4.25', None, None]","['cans', 'tablespoons', 'tablespoons', 'tables..."

In [32]:
ingr_df.food = ingr_df.food.apply(ast.literal_eval)
ingr_df

,title,food,quantity,unit
0,Infineon Raceway Baked Beans,"[skirt steak, pepper, bacon, onion, jalapenos,...","['2', None, 'about 1', '1 1/2', '2', '3', '1',...","['pounds', None, 'cup', 'cups', 'cup', 'tables..."
1,Sour Cream Noodle Bake,"[chuck, tomato sauce, salt, pepper, egg noodle...","['1 1/4', '15', '1/2', None, '8', '1/2', '1 1/...","['pounds', 'can', 'teaspoon', None, 'ounces', ..."
2,Middle-Eastern Eggplant Rounds,"[olive oil, baby Italian eggplants, Kosher sal...","['1', '6', None, '1/2', '4', '2', '1']","['tablespoon', 'ounces', None, 'cup', None, 't..."
3,Saffron Jewel Rice,"[saffron threads, sugar, Kosher salt, orange z...","['1/2', '1/3', None, '2', '1', '4', '1', '1', ...","['teaspoon', 'cup', None, 'strips', None, 'tab..."
4,Thai Sweet and Sour Wings,"[chili sauce, rice vinegar, Asian fish sauce, ...","['2', '1', '2', '1', '1', '2', None, '1', '18 ...","['cups', 'cup', 'tablespoons', 'tablespoon', '..."
...,...,...,...,...
30920,Spicy Agave Wave,"[Ice, jalapeno, lime juice, lemon juice, tequi...","[None, '1', '1-', '1/2-ounce', '1 1/2', '3/4',...","[None, 'slice', 'ounce', None, 'ounces', 'ounc..."
30921,Apple Chimichangas,"[butter, sugar, cinnamon, apple, pear, tequila...","['1/4', '1/3', '1', '1', '1', '1/4', '4', '1',...","['cup', 'cup', 'teaspoon', None, None, 'cup', ..."
30922,Summer Corn Salad,"[corn, Belgian endive, olive oil, pepper, cila...","['4', '2', '2', None, '3', '1/2', '1/4', '1/2'...","['ears', 'heads', 'tablespoons', None, 'bunch'..."
30923,Zucchini Stuffed Tomatoes,"[plum tomatoes, sugar, zucchini, salt, shallot...","['4', None, '1 1/2', '1', '3', '2', '3', '1 1/...","[None, None, 'pounds', 'teaspoon', None, 'tabl..."
30924,Crabby Bisque,"[crab bisque, heavy cream, lemon juice, parsle...","['10.5', '6', '3', '3', '4.25', None, None]","['cans', 'tablespoons', 'tablespoons', 'tables..."

In [35]:
# Lowercase all ingredients
ingr_df.food = ingr_df.food.apply(lambda x: [i.lower() for i in x if type(i) == str])

In [36]:
ingr_df

,title,food,quantity,unit
0,Infineon Raceway Baked Beans,"[skirt steak, pepper, bacon, onion, jalapenos,...","['2', None, 'about 1', '1 1/2', '2', '3', '1',...","['pounds', None, 'cup', 'cups', 'cup', 'tables..."
1,Sour Cream Noodle Bake,"[chuck, tomato sauce, salt, pepper, egg noodle...","['1 1/4', '15', '1/2', None, '8', '1/2', '1 1/...","['pounds', 'can', 'teaspoon', None, 'ounces', ..."
2,Middle-Eastern Eggplant Rounds,"[olive oil, baby italian eggplants, kosher sal...","['1', '6', None, '1/2', '4', '2', '1']","['tablespoon', 'ounces', None, 'cup', None, 't..."
3,Saffron Jewel Rice,"[saffron threads, sugar, kosher salt, orange z...","['1/2', '1/3', None, '2', '1', '4', '1', '1', ...","['teaspoon', 'cup', None, 'strips', None, 'tab..."
4,Thai Sweet and Sour Wings,"[chili sauce, rice vinegar, asian fish sauce, ...","['2', '1', '2', '1', '1', '2', None, '1', '18 ...","['cups', 'cup', 'tablespoons', 'tablespoon', '..."
...,...,...,...,...
30920,Spicy Agave Wave,"[ice, jalapeno, lime juice, lemon juice, tequi...","[None, '1', '1-', '1/2-ounce', '1 1/2', '3/4',...","[None, 'slice', 'ounce', None, 'ounces', 'ounc..."
30921,Apple Chimichangas,"[butter, sugar, cinnamon, apple, pear, tequila...","['1/4', '1/3', '1', '1', '1', '1/4', '4', '1',...","['cup', 'cup', 'teaspoon', None, None, 'cup', ..."
30922,Summer Corn Salad,"[corn, belgian endive, olive oil, pepper, cila...","['4', '2', '2', None, '3', '1/2', '1/4', '1/2'...","['ears', 'heads', 'tablespoons', None, 'bunch'..."
30923,Zucchini Stuffed Tomatoes,"[plum tomatoes, sugar, zucchini, salt, shallot...","['4', None, '1 1/2', '1', '3', '2', '3', '1 1/...","[None, None, 'pounds', 'teaspoon', None, 'tabl..."
30924,Crabby Bisque,"[crab bisque, heavy cream, lemon juice, parsle...","['10.5', '6', '3', '3', '4.25', None, None]","['cans', 'tablespoons', 'tablespoons', 'tables..."

In [37]:
food_freq = {}
for food in tqdm(ingr_df.food):
    for ingr in food:
        if ingr in food_freq:
            food_freq[ingr] += 1
        else:
            food_freq[ingr] = 1

100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 30925/30925 [00:00<00:00, 272462.10it/s]

In [84]:
food_freq_df = pd.DataFrame.from_dict(food_freq, orient='index')

In [85]:
food_freq_df["ingr"] = food_freq_df.index
food_freq_df.reset_index(drop=True, inplace=True)

In [86]:
food_freq_df.columns = ["freq", "ingr"]
food_freq_df = food_freq_df[food_freq_df.columns[::-1]]
food_freq_df.sort_values('freq', ascending=True, inplace=True)
food_freq_df

                               ingr   freq
16960               kojuchang sauce      1
7188             all- purpose flour      1
12294                     bbq spice      1
12293  santa maria-style seasonings      1
7191            from 2 ears of corn      1
...                             ...    ...
5                            garlic   9931
24                        olive oil  11035
33                           butter  11529
10                            sugar  12647
1                            pepper  17490

[16961 rows x 2 columns]

In [87]:
food_freq_df[food_freq_df.freq > 50]

                   ingr   freq
1721   red chile flakes     51
221      canadian bacon     51
758           cornbread     51
1651  flat leaf parsley     51
885     wonton wrappers     52
...                 ...    ...
5                garlic   9931
24            olive oil  11035
33               butter  11529
10                sugar  12647
1                pepper  17490

[585 rows x 2 columns]

In [88]:
food_freq_df[food_freq_df.freq > 50].to_csv('../data/ingr_candidate_freq_50.csv', index=False)